### PR TITLE
es6, node>=6, mapbox namespace

### PR DESCRIPTION
**Pull request by mapsam**
Providing a few updates to this module, specifically:

* es6 syntax - biggest changes are using `class/extends` instead of prototype inheritance
* eslint only (no more jshint) - including linting updates
* test on node 6, 8, 10
* using the `@mapbox/mapbox-error` namespace
* removed circleci webhook so we just test w/ travis now

cc @mapbox/maps-api

### CODE REVIEW

**Comment by mapsam** [comment]
@norchard @millzpaugh @ian29 thinking this should be a major release since we're explicitly breaking in node <5 - thoughts?

**Comment by millzpaugh** [comment]
@mapsam 👍

**Comment by mapsam** [comment]
👍 going with 3.0.0

**Comment by riastrad** [comment]
> removed circleci webhook so we just test w/ travis now

Not sure what happened here, but I was just haunted by the ghost of circleci over in #19. I removed the webhook again, but just wanted to flag here for posterity.

**Pull request merged**
